### ISSUE TITLE
Error running i3-quake

### ISSUE THREAD

**Issue by VasilyKrylov** [NearHuscarl/i3-quake#1]
Hello! I've installed all depencies and download i3-quake to home directory, run it and got this error message:

```
Backup > ./i3-quake -H 0.6 -t alacritty htop
Traceback (most recent call last):
  File "/home/vasily/Backup/./i3-quake", line 166, in <module>
    toggle_quake(args.term, args.pos, args.ratio, args.cmd)
  File "/home/vasily/Backup/./i3-quake", line 107, in toggle_quake
    quake_term = i3.get_tree().find_named(get_name())
                                          ^^^^^^^^^^
  File "/home/vasily/Backup/./i3-quake", line 90, in get_name
    ws_num = get_current_workspace()['num']
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vasily/Backup/./i3-quake", line 79, in get_current_workspace
    return [ws for ws in i3.get_workspaces() if ws['focused']][0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vasily/Backup/./i3-quake", line 79, in <listcomp>
    return [ws for ws in i3.get_workspaces() if ws['focused']][0]
                                                ~~^^^^^^^^^^^
TypeError: 'WorkspaceReply' object is not subscriptable
```

But -h option works:
```
Backup > ./i3-quake -h
usage: i3-quake [-h] [-i] [-p POS] [-H RATIO] [-t TERM] [CMD]

positional arguments:
  CMD                   command to execute in new terminal

options:
  -h, --help            show this help message and exit
  -i, --in-place        set current terminal at top down position and
                        execute cmd
  -p POS, --pos POS     open terminal at top or bottom (default is top)
  -H RATIO, --height RATIO
                        height of terminal in percentage of monitor height
  -t TERM, --term TERM  terminal name (default is xterm)
```

I use Fedora 37 Workstation with i3

Developer, if you need any other debug info, which I forgot, wright down about it

Thanks

**Comment by joaothallis** [comment]
I am having the same issue, I am using Ubuntu 22.04.3 LTS x86_64

**Comment by GeneralBison** [comment]
I've fixed this error in my [pull request](https://github.com/NearHuscarl/i3-quake/pull/2), only requires 6 lines to be changed. Have fun!
